locale: fr
publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
media_folder: public/media
public_folder: /media
collections:
- name: blog
  label: Article
  folder: posts
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
  - label: Layout
    name: layout
    widget: hidden
    default: blog
  - label: Titre
    name: title
    widget: string
  - label: Date de publication
    name: date
    widget: datetime
  - label: Couverture
    name: thumbnail
    widget: image
  - label: Contenu
    name: body
    widget: markdown
